name: hermes
description: Messaging library for Dart. Nimble and efficient like the messenger of the Gods.
version: 3.0.0
homepage: https://www.github.com/xenoken/hermes
repository: https://www.github.com/xenoken/hermes
author: Ken Ekeoha <ekeohak@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
